@APIURL=http://localhost:8080
@AccessToken = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJubXJvbnkiLCJST0xFUyI6WyJST0xFX1VTRVIiLCJST0xFX0FETUlOIl0sImlzcyI6InNlY3VyZS5ubXJvbnkuaW5mbyIsImV4cCI6MTYxNjM1NjY2NCwiaWF0IjoxNjE1NzUxODY0fQ.oLIv0GLMVx-pFRV4xAKOk8rTSfpBxggjGlkCFWebAdkciD_81utIQJBHh6CVd-pDcGvLvP9P-T5LblHUk0sMdw

POST {{APIURL}}/api/users/register HTTP/1.1
Content-Type: application/json

{
  "firstName": "Nur",
  "lastName": "Rony",
  "password": "123456",
  "confirmPassword": "123456",
  "email": "tofazzal@nmrony.info",
  "username": "nmrony",
  "roles": [{"name": "ROLE_ADMIN"}, {"name": "ROLE_USER"}]
}

###
POST {{APIURL}}/api/auth/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "nmrony",
  "password": "123456"
}

###
GET {{APIURL}}/api/mod HTTP/1.1
Content-Type: application/json
#Authorization: {{AccessToken}}
###
GET {{APIURL}}/api/admin/users HTTP/1.1
Content-Type: application/json
Authorization: {{AccessToken}}

###
GET {{APIURL}}/api/users HTTP/1.1
Content-Type: application/json
Authorization: {{AccessToken}}
